/**
 * Property test on the mainnet fork (real stockfloor, DBC 0.2.1, DAMM v2 0.2.4, Token-2022, SPYx):
 * random action sequences after graduation, generated by fast-check with a fixed seed and a bounded
 * number of runs, so every CI run replays the same sequences.
 *
 * Each run starts from a fresh fork with a graduated launch (migration fee harvested) and five
 * holders (two curve buyers, the completing buyer, two DAMM v2 traders), then applies 10 to 40
 * actions drawn from: redeem (fraction of a balance, or a raw dust amount), SPYx donation to the
 * vault, base donation to the claimer burned in the same transaction, harvest_curve_fees,
 * harvest_lp_fees, harvest_surplus, DAMM v2 buys and sells, clock warps and ScaledUiAmount
 * multiplier changes (cheatcode).
 *
 * After every action (FloorTracker plus an independent model of vault and supply):
 * - the floor never decreases (cross-multiplication), strictly rises on a redeem with a fee;
 * - quote leaves the vault only through a redeem, by exactly the redeemer's net
 *   (`floor(V·a/S) − ceil(floor(V·a/S)·bps/1e4)`); every other action leaves it equal or higher by
 *   exactly the harvested / donated amount;
 * - `mint.supply` equals the sum of all base holdings (DBC base vault, DAMM v2 base vault, holders,
 *   claimer base ATA) and the model supply;
 * - the claimer holds no base tokens;
 * - the vault is owned by the vault authority, with no delegate and no close authority.
 * Rejected actions (NothingToRedeem, ZeroAmount, SurplusAlreadyHarvested, a DAMM v2 swap that DAMM
 * refuses) must change nothing.
 */
import { createTransferCheckedInstruction, createTransferInstruction } from "@solana/spl-token";
import { Keypair } from "@solana/web3.js";
import fc from "fast-check";
import { describe, expect, it } from "vitest";
import { parseEvents } from "../src/anchor.js";
import { SPYX_DECIMALS, SPYX_MINT, TOKEN_2022_PROGRAM_ID, TOKEN_PROGRAM_ID } from "../src/constants.js";
import { dammSwap2Ix, fetchDammPool, fetchPosition } from "../src/damm.js";
import { bnToBig, fetchVirtualPool } from "../src/dbc.js";
import { FloorTracker } from "../src/floor-invariants.js";
import { anchorErrorFromLogs, Fork, TxResult } from "../src/fork.js";
import { fundedWallet, Migration } from "../src/scenario.js";
import { createStockfloorLaunch, graduate, StockfloorLaunch, trackerAccounts } from "../src/stockfloor-scenario.js";
import {
  burnClaimerBaseIx,
  fetchLaunch,
  harvestCurveFeesIx,
  harvestLpFeesIx,
  harvestMigrationFeeIx,
  harvestSurplusIx,
  redeemIx,
  stockfloorProgram,
} from "../src/stockfloor.js";
import { createAta, createAtaIdempotentIx, fundSpyx, mintSupply, setScaledUiMultiplier, splAta, spyxAta, tokenAmount } from "../src/token.js";

const SEED = 20_260_915;
const NUM_RUNS = 40;
const MAX_ACTIONS = 40;
const HOLDERS = 5;
const BPS = 200n;
const ceilDiv = (a: bigint, b: bigint) => (a + b - 1n) / b;
const U128 = 1n << 128n;
const u256le = (bytes: number[] | Uint8Array) => BigInt("0x" + (Buffer.from(bytes).reverse().toString("hex") || "0"));
const errOf = (r: TxResult) => (r.ok ? "OK" : anchorErrorFromLogs(r.logs)?.name ?? r.error);

type Action =
  | { kind: "redeem"; holder: number; bps: number }
  | { kind: "redeemRaw"; holder: number; amount: bigint }
  | { kind: "donateQuote"; amount: bigint }
  | { kind: "donateBaseAndBurn"; holder: number; bps: number }
  | { kind: "harvestCurve" }
  | { kind: "harvestLp" }
  | { kind: "harvestSurplus" }
  | { kind: "swapBuy"; holder: number; quote: bigint }
  | { kind: "swapSell"; holder: number; bps: number }
  | { kind: "warp"; seconds: number }
  | { kind: "multiplier"; value: number };

const holder = fc.integer({ min: 0, max: HOLDERS - 1 });
const bps = fc.integer({ min: 1, max: 10_000 });
const actionArb: fc.Arbitrary<Action> = fc.oneof(
  { weight: 6, arbitrary: fc.record({ kind: fc.constant("redeem" as const), holder, bps }) },
  { weight: 2, arbitrary: fc.record({ kind: fc.constant("redeemRaw" as const), holder, amount: fc.bigInt({ min: 1n, max: 100_000_000n }) }) },
  { weight: 2, arbitrary: fc.record({ kind: fc.constant("donateQuote" as const), amount: fc.bigInt({ min: 1n, max: 20_000_000n }) }) },
  { weight: 2, arbitrary: fc.record({ kind: fc.constant("donateBaseAndBurn" as const), holder, bps }) },
  { weight: 2, arbitrary: fc.constant({ kind: "harvestCurve" as const }) },
  { weight: 2, arbitrary: fc.constant({ kind: "harvestLp" as const }) },
  { weight: 1, arbitrary: fc.constant({ kind: "harvestSurplus" as const }) },
  { weight: 4, arbitrary: fc.record({ kind: fc.constant("swapBuy" as const), holder, quote: fc.bigInt({ min: 1_000n, max: 30_000_000n }) }) },
  { weight: 3, arbitrary: fc.record({ kind: fc.constant("swapSell" as const), holder, bps }) },
  { weight: 1, arbitrary: fc.record({ kind: fc.constant("warp" as const), seconds: fc.integer({ min: 1, max: 86_400 }) }) },
  { weight: 1, arbitrary: fc.record({ kind: fc.constant("multiplier" as const), value: fc.double({ min: 0.5, max: 2, noNaN: true }) }) },
);

interface World {
  fork: Fork;
  L: StockfloorLaunch;
  migration: Migration;
  holders: Keypair[];
  cranker: Keypair;
  tracker: FloorTracker;
  vault: bigint; // model
  supply: bigint; // model
  netOut: bigint; // model: sum of redeem payouts
}

async function setup(): Promise<World> {
  const fork = Fork.create({ stockfloor: true, spike: false });
  const L = await createStockfloorLaunch(fork, { exitFeeBps: Number(BPS) });
  const g = await graduate(fork, L, [25n, 15n]);
  const cranker = fork.newWallet(100);
  fork.send([await harvestMigrationFeeIx({ keys: L.keys })], [cranker]);
  const traders = [fundedWallet(fork, 10n * L.threshold), fundedWallet(fork, 10n * L.threshold)];
  const holders = [...g.buyers, g.whale, ...traders];
  expect(holders.length).toBe(HOLDERS);
  for (const h of holders) {
    fundSpyx(fork, h, h.publicKey, 5n * L.threshold);
    createAta(fork, h, h.publicKey, L.keys.baseMint, TOKEN_PROGRAM_ID);
  }
  fork.warp(60);
  const tracker = new FloorTracker(fork, trackerAccounts(L));
  tracker.trackBase(L.keys.baseVault, g.migration.tokenAVault, ...holders.map((h) => splAta(h.publicKey, L.keys.baseMint)));
  tracker.start("run start");
  return { fork, L, migration: g.migration, holders, cranker, tracker, vault: tokenAmount(fork, L.vault), supply: mintSupply(fork, L.keys.baseMint), netOut: 0n };
}

const stats: Record<string, { ok: number; rejected: number }> = {};
const count = (kind: string, ok: boolean) => {
  stats[kind] ??= { ok: 0, rejected: 0 };
  stats[kind][ok ? "ok" : "rejected"]++;
};

/** Apply one action, checking its exact effect against the model; the tracker checks the invariants. */
async function apply(w: World, a: Action, i: number): Promise<void> {
  const { fork, L } = w;
  const label = `#${i} ${JSON.stringify(a, (_k, v) => (typeof v === "bigint" ? v.toString() : v))}`;
  const baseOf = (k: number) => splAta(w.holders[k].publicKey, L.keys.baseMint);
  const unchanged = (r: TxResult, expected: string[]) => {
    expect(r.ok, label).toBe(false);
    expect(expected, `${label}: ${errOf(r)}`).toContain(errOf(r));
  };

  switch (a.kind) {
    case "redeem":
    case "redeemRaw": {
      const h = w.holders[a.holder];
      const balance = tokenAmount(fork, baseOf(a.holder));
      const amount = a.kind === "redeem" ? (balance * BigInt(a.bps)) / 10_000n : a.amount;
      const V = w.vault;
      const S = w.supply;
      const gross = S > 0n && amount <= S ? (V * amount) / S : 0n;
      const fee = ceilDiv(gross * BPS, 10_000n);
      const net = gross - fee;
      const valid = amount > 0n && amount <= balance && net > 0n;
      const q0 = tokenAmount(fork, spyxAta(h.publicKey));
      let r: TxResult | undefined;
      await w.tracker.step(label, valid ? "redeem" : "no-outflow", async () => {
        r = fork.sendTx([await redeemIx({ holder: h.publicKey, keys: L.keys, amount })], [h]);
      }, valid ? { vaultOut: net, feeRetained: fee } : {});
      count(a.kind, valid);
      if (!valid) {
        unchanged(r!, amount === 0n ? ["ZeroAmount"] : amount > balance ? ["InsufficientBaseBalance"] : ["NothingToRedeem"]);
        return;
      }
      expect(r!.ok, `${label}: ${errOf(r!)}`).toBe(true);
      expect(tokenAmount(fork, spyxAta(h.publicKey)) - q0, label).toBe(net);
      w.vault -= net;
      w.supply -= amount;
      w.netOut += net;
      return;
    }
    case "donateQuote": {
      const donor = w.holders[0];
      await w.tracker.step(label, "no-outflow", () =>
        fork.send([createTransferCheckedInstruction(spyxAta(donor.publicKey), SPYX_MINT, L.vault, donor.publicKey, a.amount, SPYX_DECIMALS, [], TOKEN_2022_PROGRAM_ID)], [donor]),
      );
      count(a.kind, true);
      w.vault += a.amount;
      return;
    }
    case "donateBaseAndBurn": {
      const h = w.holders[a.holder];
      const amount = (tokenAmount(fork, baseOf(a.holder)) * BigInt(a.bps)) / 10_000n;
      // One transaction: create the claimer base ATA if needed, donate, burn. The claimer never ends
      // a transaction holding base.
      const res = await w.tracker.step(label, "no-outflow", async () =>
        fork.send(
          [
            createAtaIdempotentIx(h.publicKey, L.claimer, L.keys.baseMint, TOKEN_PROGRAM_ID),
            createTransferInstruction(baseOf(a.holder), L.claimerBaseAccount, h.publicKey, amount),
            await burnClaimerBaseIx({ config: L.config, baseMint: L.keys.baseMint }),
          ],
          [h],
        ),
      );
      count(a.kind, true);
      const ev = parseEvents(stockfloorProgram(), res.logs).find((e) => e.name === "claimerBaseBurned");
      expect(bnToBig(ev!.data.baseBurned), label).toBe(amount);
      w.supply -= amount;
      return;
    }
    case "harvestCurve": {
      const expected = bnToBig(fetchVirtualPool(fork, L.keys.pool).partnerQuoteFee);
      await w.tracker.step(label, "no-outflow", async () => fork.send([await harvestCurveFeesIx({ payer: w.cranker.publicKey, keys: L.keys })], [w.cranker]));
      count(a.kind, true);
      w.vault += expected;
      return;
    }
    case "harvestLp": {
      const pool = fetchDammPool(fork, w.migration.dammPool);
      const pos = fetchPosition(fork, w.migration.firstPosition);
      const liq = bnToBig(pos.unlockedLiquidity) + bnToBig(pos.vestedLiquidity) + bnToBig(pos.permanentLockedLiquidity);
      const expectedB = bnToBig(pos.feeBPending) + (liq * (u256le(pool.feeBPerLiquidity) - u256le(pos.feeBPerTokenCheckpoint))) / U128;
      const expectedA = bnToBig(pos.feeAPending) + (liq * (u256le(pool.feeAPerLiquidity) - u256le(pos.feeAPerTokenCheckpoint))) / U128;
      expect(expectedA, label).toBe(0n); // quote-only LP fees
      await w.tracker.step(label, "no-outflow", async () =>
        fork.send(
          [
            await harvestLpFeesIx({
              payer: w.cranker.publicKey,
              keys: L.keys,
              dammPool: w.migration.dammPool,
              position: w.migration.firstPosition,
              positionNftAccount: w.migration.firstPositionNftAccount,
              dammTokenAVault: w.migration.tokenAVault,
              dammTokenBVault: w.migration.tokenBVault,
            }),
          ],
          [w.cranker],
        ),
      );
      count(a.kind, true);
      w.vault += expectedB;
      return;
    }
    case "harvestSurplus": {
      const already = fetchLaunch(fork, L.config).surplusHarvested as boolean;
      const surplus = bnToBig(fetchVirtualPool(fork, L.keys.pool).quoteReserve) - L.threshold;
      const pc = (surplus * 80n) / 100n;
      const expected = pc - (pc * 30n) / 100n;
      let r: TxResult | undefined;
      await w.tracker.step(label, "no-outflow", async () => {
        r = fork.sendTx([await harvestSurplusIx({ keys: L.keys })], [w.cranker]);
      });
      count(a.kind, !already);
      if (already) return unchanged(r!, ["SurplusAlreadyHarvested"]);
      expect(r!.ok, `${label}: ${errOf(r!)}`).toBe(true);
      w.vault += expected;
      return;
    }
    case "swapBuy":
    case "swapSell": {
      const h = w.holders[a.holder];
      const amount = a.kind === "swapBuy" ? a.quote : (tokenAmount(fork, baseOf(a.holder)) * BigInt(a.bps)) / 10_000n;
      const [input, output] = a.kind === "swapBuy" ? [spyxAta(h.publicKey), baseOf(a.holder)] : [baseOf(a.holder), spyxAta(h.publicKey)];
      let r: TxResult | undefined;
      await w.tracker.step(label, "no-outflow", async () => {
        r = fork.sendTx(
          [await dammSwap2Ix({ keys: w.migration.dammKeys, payer: h.publicKey, inputTokenAccount: input, outputTokenAccount: output, amount0: amount, amount1: 0n, swapMode: 0 })],
          [h],
        );
      });
      // A swap DAMM v2 refuses (e.g. a zero or dust amount) must change nothing, which the tracker and
      // the model check below; accepted swaps never touch the vault or the supply.
      count(a.kind, r!.ok);
      return;
    }
    case "warp":
      await w.tracker.step(label, "no-outflow", () => fork.warp(a.seconds));
      count(a.kind, true);
      return;
    case "multiplier":
      await w.tracker.step(label, "no-outflow", () => setScaledUiMultiplier(fork, SPYX_MINT, a.value));
      count(a.kind, true);
      return;
  }
}

describe("fork property: random redeem / donation / harvest / DAMM v2 sequences keep every floor invariant", () => {
  it(`fast-check seed ${SEED}, ${NUM_RUNS} runs of up to ${MAX_ACTIONS} actions`, async () => {
    let runs = 0;
    let actions = 0;
    let redeemedNet = 0n;
    await fc.assert(
      fc.asyncProperty(fc.array(actionArb, { minLength: 10, maxLength: MAX_ACTIONS, size: "max" }), async (seq) => {
        const w = await setup();
        const outflowBefore = bnToBig(fetchLaunch(w.fork, w.L.config).totalRedeemedQuote);
        for (let i = 0; i < seq.length; i++) {
          await apply(w, seq[i], i);
          // The model agrees with the chain after every action.
          expect(tokenAmount(w.fork, w.L.vault), `model vault after #${i}`).toBe(w.vault);
          expect(mintSupply(w.fork, w.L.keys.baseMint), `model supply after #${i}`).toBe(w.supply);
        }
        const launch = fetchLaunch(w.fork, w.L.config);
        // The program's own outflow counter equals the model's sum of exact redeem payouts.
        expect(bnToBig(launch.totalRedeemedQuote) - outflowBefore).toBe(w.netOut);
        runs++;
        actions += seq.length;
        redeemedNet += w.netOut;
      }),
      { seed: SEED, numRuns: NUM_RUNS, endOnFailure: true },
    );
    expect(runs).toBe(NUM_RUNS);
    console.log(JSON.stringify({ floorProperty: { seed: SEED, runs, actions, redeemedNet, stats } }, (_k, v) => (typeof v === "bigint" ? v.toString() : v)));
    // The generator reached every action kind, and redemptions really happened.
    for (const k of ["redeem", "redeemRaw", "donateQuote", "donateBaseAndBurn", "harvestCurve", "harvestLp", "harvestSurplus", "swapBuy", "swapSell", "warp", "multiplier"]) {
      expect(stats[k]?.ok ?? 0, `action ${k} succeeded at least once`).toBeGreaterThan(0);
    }
    expect(stats.redeem.ok).toBeGreaterThan(20);
  });
});
